name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate kube configuration
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "${{ secrets.AKS_CONTEXT }}" >> ~/.kube/config

#       - name: Create secrets
#         run: |
#           kubectl delete configmap env-configmap --ignore-not-found
#           kubectl create configmap env-configmap --from-literal=env.js=${{ secrets.ENV_SECRETS }}

      - name: Deploy application
        run: kubectl apply -f kubernetes/deployment.yaml

      - name: Restart pod
        run: kubectl rollout restart deploy xmp-manager-deployment
